version: 0.0
os: linux
files:
  - source: target/hello-world.war
    destination: /opt/tomcat/webapps/
hooks:
  ApplicationStop:
    - location: scripts/stop_application
      timeout: 400
  ApplicationStart:
    - location: scripts/start_application
      timeout: 400