version: 0.0
os: linux
files:
  - source: hello-world.war
    destination: /opt/tomcat/webapps/
hooks:
  ApplicationStop:
    - location: scripts/stop_application
      timeout: 300
	  runas: root

  ApplicationStart:
    - location: scripts/start_application
      timeout: 300
	  runas: root