version: 0.0
os: linux
files:
  - source: hello-world.war
    destination: /opt/tomcat/webapps/

hooks:
  ApplicationStop:
    - location: stop_application
      timeout: 300

  ApplicationStart:
    - location: start_application
      timeout: 300
